{% set name = "stopt" %}
{% set version = "5.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/stochastic-control/{{ name }}/-/archive/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: 46b4e0ea223e24c846653f648dde313f6a8a1f35fa5f7e00b2cb686df30a9cfb

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('stopt') }} 

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake >=3.15
    - _openmp_mutex  # [linux]
    - llvm-openmp  # [osx]
    - make
    - pkgconfig  # [unix]
    - ninja  # [win]
  host:
    - libboost-headers
    - libboost-mpi
    - mpich  # [unix]
    - msmpi  # [win]
    - _openmp_mutex  # [linux]
    - llvm-openmp  # [osx]
    - eigen
    - coin-or-utils
    - coin-or-clp
    - coin-or-osi
    - bzip2
    - zlib
  run:
    - libboost

test:
  commands:
    - test -f $PREFIX/lib/libStOpt.so  # [linux]
    - test -f $PREFIX/lib/libgeners.so  # [linux]
    - test -f $PREFIX/lib/libStOpt.dylib  # [osx]
    - test -f $PREFIX/lib/libgeners.dylib  # [osx]
    - if not exist "%PREFIX%\\Library\\lib\\StOpt.lib" exit 1  # [win]
    - if not exist "%PREFIX%\\Library\\lib\\geners.lib" exit 1  # [win]

about:
  home: https://gitlab.com/stochastic-control/StOpt
  summary: 'Library for stochastic control'
  description: |
    The STochastic OPTimization library (StOpt) aims at providing tools in C++ for solvingsome stochastic optimization problems encountered in finance or in the industry.
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  doc_url: https://gitlab.com/stochastic-control/StOpt
  dev_url: https://gitlab.com/stochastic-control/StOpt

extra:
  recipe-maintainers:
    - davide-f
    - XWarin
